### PR TITLE
Migrating the provider to the Terraform Plugin SDK.

### PR DESCRIPTION
**Pull request by lazzurs**
Migrating the provider to the Terraform Plugin SDK using the automated
migration tool.

Build and tests pass.

### CODE REVIEW

**Comment by likexian** [comment]
Hello @lazzurs 
The CI tests fail, would you please fix it?

**Comment by lazzurs** [comment]
@likexian The lint test is failing. This is due to the change to the SDK. I can either exclude Set from the tests or check the errors on each use of Set. What would you rather I do?

**Comment by likexian** [comment]
> @likexian The lint test is failing. This is due to the change to the SDK. I can either exclude Set from the tests or check the errors on each use of Set. What would you rather I do?

Hello @lazzurs:
```_ = d.Set(...)``` please.
Thank you.

**Comment by lazzurs** [comment]
Fixed the linting errors and updated to latest master branch. Should merge and work now.

**Comment by likexian** [comment]
Hello @lazzurs 
Thanks for your works.

**Pull request merged**
